# -*- coding: utf-8 -*-
r"""
Hierarchical Langevin simulation consistent with type-A nested superstatistics.

The theoretical type-A weights are f_A(beta|n) and h_A(n). Since the
Langevin process samples locally normalized Gaussian distributions, the
environmental variables must be sampled from the corresponding residence
densities

    rho(beta|n) proportional to Z_u(beta) f_A(beta|n),
    rho_n(n)    proportional to Z_A(n) h_A(n).

With these residence densities, the stationary marginal generated by the
Langevin dynamics is the normalized type-A nested distribution.

Outputs
-------
Fig-Langevin.pdf
Fig-Langevin.png
Fig-Langevin-data.npz
Fig-Langevin-parameters.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from scipy.special import gammaln


# ============================================================
# 1. Plot style
# ============================================================

mpl.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica", "Arial", "DejaVu Sans"],
    "font.size": 14,
    "axes.labelsize": 14,
    "xtick.labelsize": 14,
    "ytick.labelsize": 14,
    "legend.fontsize": 11,
    "text.color": "black",
    "axes.labelcolor": "black",
    "axes.edgecolor": "black",
    "xtick.color": "black",
    "ytick.color": "black",
    "axes.linewidth": 1.1,
    "xtick.direction": "in",
    "ytick.direction": "in",
    "xtick.top": True,
    "ytick.right": True,
    "xtick.major.size": 5,
    "ytick.major.size": 5,
    "xtick.minor.size": 3,
    "ytick.minor.size": 3,
    "lines.linewidth": 2.2,
    "legend.frameon": False,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})


# ============================================================
# 2. Physical and numerical parameters
# ============================================================

beta0 = 1.0
gamma = 1.0
tau_v = 1.0 / gamma

# Nominal value n0 = 2/(q_nominal-1).
q_nominal = 1.20
n0 = 2.0 / (q_nominal - 1.0)

# Width of the parent log-normal type-A weight h_A(n).
sigma_eta = 0.35

# The normalized type-A velocity distribution requires n>1.
# We impose n>5 so that the fourth moment used in Appendix B also exists.
n_min = 5.05

# Time step.
dt = 0.02

# Slow trajectory: stronger time-scale separation and longer sampling.
slow_tau_beta = 50.0
slow_tau_n = 500.0
slow_n_steps = 5_000_000
slow_burn = 100_000

# Fast trajectory: same residence distributions, reduced time-scale separation.
fast_tau_beta = 0.02
fast_tau_n = 0.10
fast_n_steps = 1_500_000
fast_burn = 50_000

# Monte Carlo size of the adiabatic reference.
n_ref_samples = 2_000_000

# At least this many tail events are required in each sample for the ratio plot.
min_tail_counts = 100


# ============================================================
# 3. Type-A residence distributions
# ============================================================

def log_Z_A(n: np.ndarray | float) -> np.ndarray:
    """
    Logarithm of the fixed-n normalization of the type-A factor.

    For E=u^2/beta0,

        B_n(E) = (1 + 2u^2/n)^(-n/2),

    and

        Z_A(n) = integral B_n(u^2/beta0) du
               = sqrt(pi n/2) Gamma[(n-1)/2] / Gamma[n/2].
    """

    n = np.asarray(n, dtype=float)
    if np.any(n <= 1.0):
        raise ValueError("Z_A(n) is finite only for n>1.")

    return (
        0.5 * np.log(np.pi * n / 2.0)
        + gammaln((n - 1.0) / 2.0)
        - gammaln(n / 2.0)
    )


class NResidenceSampler:
    """
    Inverse-CDF sampler for rho_n(n) proportional to h_A(n) Z_A(n).

    The prescribed type-A weight h_A(n) is a log-normal distribution,
    conditioned on n>=n_min.
    """

    def __init__(
        self,
        n0: float,
        sigma_eta: float,
        n_min: float,
        grid_size: int = 50_000,
    ) -> None:
        self.n0 = float(n0)
        self.sigma_eta = float(sigma_eta)
        self.n_min = float(n_min)

        # Parent log-normal:
        # ln n ~ Normal(mu, sigma_eta^2), with untruncated mean n0.
        mu = np.log(self.n0) - 0.5 * self.sigma_eta**2
        y_min = np.log(self.n_min)
        y_max = max(
            mu + 8.0 * self.sigma_eta,
            y_min + 8.0 * self.sigma_eta,
        )

        y_grid = np.linspace(y_min, y_max, grid_size)
        n_grid = np.exp(y_grid)

        # In y=ln n, the Jacobian is already included in the Gaussian density.
        log_density = (
            -0.5 * ((y_grid - mu) / self.sigma_eta) ** 2
            + log_Z_A(n_grid)
        )
        density = np.exp(log_density - np.max(log_density))

        increments = (
            0.5
            * (density[1:] + density[:-1])
            * np.diff(y_grid)
        )
        cdf = np.concatenate(([0.0], np.cumsum(increments)))
        cdf /= cdf[-1]

        self._y_grid = y_grid
        self._cdf = cdf

    def sample(
        self,
        rng: np.random.Generator,
        size: int | None = None,
    ) -> np.ndarray | float:
        """Draw samples from rho_n(n)."""

        uniforms = rng.random(size=size)
        y = np.interp(uniforms, self._cdf, self._y_grid)
        return np.exp(y)


n_residence_sampler = NResidenceSampler(
    n0=n0,
    sigma_eta=sigma_eta,
    n_min=n_min,
)


def sample_beta_residence(
    rng: np.random.Generator,
    n: np.ndarray | float,
) -> np.ndarray | float:
    """
    Draw beta from rho(beta|n).

    For the one-dimensional Langevin realization,

        rho(beta|n) = Gamma(shape=(n-1)/2, scale=2 beta0/n).
    """

    n = np.asarray(n, dtype=float)
    shape = (n - 1.0) / 2.0
    scale = 2.0 * beta0 / n
    return rng.gamma(shape=shape, scale=scale)


# ============================================================
# 4. Hierarchical Langevin simulation
# ============================================================

def simulate_langevin(
    tau_beta: float,
    tau_n: float,
    n_steps: int,
    burn: int,
    seed: int,
) -> np.ndarray:
    """Simulate the hierarchical Langevin process in dimensionless u."""

    if burn >= n_steps:
        raise ValueError("burn must be smaller than n_steps.")

    rng = np.random.default_rng(seed)

    steps_beta = max(1, int(round(tau_beta / dt)))
    steps_n = max(1, int(round(tau_n / dt)))

    if steps_n % steps_beta != 0:
        raise ValueError(
            "tau_n/tau_beta must be an integer for the renewal protocol."
        )

    # Exact Ornstein-Uhlenbeck coefficient.
    decay = np.exp(-gamma * dt)

    u = 0.0
    n = float(n_residence_sampler.sample(rng))
    beta = float(sample_beta_residence(rng, n))

    data = np.empty(n_steps - burn)
    output_index = 0

    for step in range(n_steps):

        # Slow renewal of n from rho_n(n).
        if step % steps_n == 0:
            n = float(n_residence_sampler.sample(rng))

        # Renewal of beta from rho(beta|n).
        # Since steps_n is a multiple of steps_beta, beta is also renewed
        # whenever n changes.
        if step % steps_beta == 0:
            beta = float(sample_beta_residence(rng, n))

        # Exact update of the Ornstein-Uhlenbeck process.
        noise_amplitude = np.sqrt(
            (1.0 - decay**2) * beta0 / (2.0 * beta)
        )
        u = decay * u + noise_amplitude * rng.normal()

        if step >= burn:
            data[output_index] = u
            output_index += 1

    return data


# ============================================================
# 5. Adiabatic type-A reference
# ============================================================

def adiabatic_reference(
    sample_size: int,
    seed: int,
) -> np.ndarray:
    """
    Sample the normalized type-A nested distribution directly.

    The residence hierarchy is sampled as

        n ~ rho_n(n),
        beta ~ rho(beta|n),
        u ~ Normal[0, beta0/(2 beta)].
    """

    rng = np.random.default_rng(seed)

    n = n_residence_sampler.sample(rng, size=sample_size)
    beta = sample_beta_residence(rng, n)
    u = (
        np.sqrt(beta0 / (2.0 * beta))
        * rng.normal(size=sample_size)
    )

    return u


# ============================================================
# 6. Survival functions
# ============================================================

def empirical_survival(
    absolute_data: np.ndarray,
    grid: np.ndarray,
) -> np.ndarray:
    """Efficiently compute Prob(|u|>U) on a prescribed grid."""

    sorted_data = np.sort(np.asarray(absolute_data, dtype=float))
    indices = np.searchsorted(sorted_data, grid, side="right")
    return (sorted_data.size - indices) / sorted_data.size


def moving_average(
    values: np.ndarray,
    window: int = 9,
) -> np.ndarray:
    """Centered moving average used only for the ratio panel."""

    window = int(window)
    if window < 1:
        raise ValueError("window must be positive.")

    left = window // 2
    right = window - 1 - left
    padded = np.pad(values, (left, right), mode="edge")
    kernel = np.ones(window) / window
    return np.convolve(padded, kernel, mode="valid")


# ============================================================
# 7. Figure generation
# ============================================================

def generate_figure(output_dir: Path) -> None:
    """Run the simulations and generate the two-panel figure."""

    print(f"n0 = {n0:.6f}")
    print(f"n_min = {n_min:.6f}")
    print(f"tau_v = {tau_v:.6f}")

    u_slow = simulate_langevin(
        tau_beta=slow_tau_beta,
        tau_n=slow_tau_n,
        n_steps=slow_n_steps,
        burn=slow_burn,
        seed=12345,
    )

    u_fast = simulate_langevin(
        tau_beta=fast_tau_beta,
        tau_n=fast_tau_n,
        n_steps=fast_n_steps,
        burn=fast_burn,
        seed=67890,
    )

    u_ref = adiabatic_reference(
        sample_size=n_ref_samples,
        seed=24680,
    )

    print("Slow Langevin points:", len(u_slow))
    print("Fast Langevin points:", len(u_fast))
    print("Adiabatic reference points:", len(u_ref))

    grid = np.linspace(0.0, 5.0, 250)
    S_ref = empirical_survival(np.abs(u_ref), grid)
    S_slow = empirical_survival(np.abs(u_slow), grid)
    S_fast = empirical_survival(np.abs(u_fast), grid)

    grid_ratio = np.linspace(0.0, 3.5, 150)
    S_ref_ratio = empirical_survival(np.abs(u_ref), grid_ratio)
    S_slow_ratio = empirical_survival(np.abs(u_slow), grid_ratio)
    S_fast_ratio = empirical_survival(np.abs(u_fast), grid_ratio)

    # Restrict the ratios to the range where all three samples contain
    # at least min_tail_counts events beyond U.
    mask = (
        S_ref_ratio * len(u_ref) >= min_tail_counts
    ) & (
        S_slow_ratio * len(u_slow) >= min_tail_counts
    ) & (
        S_fast_ratio * len(u_fast) >= min_tail_counts
    )

    grid_ratio_resolved = grid_ratio[mask]
    ratio_slow = (
        S_slow_ratio[mask] / S_ref_ratio[mask]
    )
    ratio_fast = (
        S_fast_ratio[mask] / S_ref_ratio[mask]
    )

    ratio_slow_smooth = moving_average(ratio_slow, window=9)
    ratio_fast_smooth = moving_average(ratio_fast, window=9)

    # Colors.
    c_ref = "black"
    c_slow = "#5DA5DA"
    c_fast = "#F28E2B"

    figure, axes = plt.subplots(1, 2, figsize=(11.2, 4.4))

    # Panel (a): survival probability.
    axis = axes[0]
    axis.plot(
        grid,
        S_ref,
        color=c_ref,
        linewidth=2.2,
        label="Adiabatic",
    )
    axis.plot(
        grid,
        S_slow,
        color=c_slow,
        linewidth=2.2,
        label="Slow Langevin",
    )
    axis.plot(
        grid,
        S_fast,
        color=c_fast,
        linewidth=2.2,
        label="Fast Langevin",
    )
    axis.set_yscale("log")
    axis.set_xlim(0.0, 5.0)
    axis.set_ylim(1.0e-5, 1.0)
    axis.set_xlabel(r"$U=|v|/v_0$")
    axis.set_ylabel(r"$S(U)=\mathrm{Prob}(|u|>U)$")
    axis.legend(loc="upper right")
    axis.tick_params(which="both", direction="in", top=True, right=True)
    axis.minorticks_on()
    axis.text(
        0.06,
        0.08,
        "(a)",
        transform=axis.transAxes,
        fontsize=14,
        color="black",
        ha="left",
        va="bottom",
    )

    # Panel (b): survival ratios.
    axis = axes[1]
    axis.plot(
        grid_ratio_resolved,
        ratio_slow_smooth,
        color=c_slow,
        linewidth=2.2,
        label="Slow / adiabatic",
    )
    axis.plot(
        grid_ratio_resolved,
        ratio_fast_smooth,
        color=c_fast,
        linewidth=2.2,
        label="Fast / adiabatic",
    )
    axis.axhline(
        1.0,
        color="black",
        linestyle="--",
        linewidth=1.1,
    )
    axis.set_xlim(0.0, 3.5)
    axis.set_ylim(0.0, 1.6)
    axis.set_xlabel(r"$U=|v|/v_0$")
    axis.set_ylabel(r"$S(U)/S_{\mathrm{ref}}(U)$")
    axis.legend(loc="upper right")
    axis.tick_params(which="both", direction="in", top=True, right=True)
    axis.minorticks_on()
    axis.text(
        0.06,
        0.08,
        "(b)",
        transform=axis.transAxes,
        fontsize=14,
        color="black",
        ha="left",
        va="bottom",
    )

    plt.tight_layout(w_pad=2.0)

    output_dir.mkdir(parents=True, exist_ok=True)

    pdf_path = output_dir / "Fig-Langevin.pdf"
    png_path = output_dir / "Fig-Langevin.png"
    data_path = output_dir / "Fig-Langevin-data.npz"
    parameters_path = output_dir / "Fig-Langevin-parameters.json"

    figure.savefig(pdf_path, bbox_inches="tight")
    figure.savefig(png_path, dpi=600, bbox_inches="tight")
    plt.close(figure)

    np.savez_compressed(
        data_path,
        grid=grid,
        S_ref=S_ref,
        S_slow=S_slow,
        S_fast=S_fast,
        grid_ratio=grid_ratio_resolved,
        ratio_slow=ratio_slow_smooth,
        ratio_fast=ratio_fast_smooth,
    )

    parameters = {
        "beta0": beta0,
        "gamma": gamma,
        "tau_v": tau_v,
        "q_nominal": q_nominal,
        "n0": n0,
        "sigma_eta": sigma_eta,
        "n_min": n_min,
        "dt": dt,
        "slow_tau_beta": slow_tau_beta,
        "slow_tau_n": slow_tau_n,
        "slow_n_steps": slow_n_steps,
        "slow_burn": slow_burn,
        "fast_tau_beta": fast_tau_beta,
        "fast_tau_n": fast_tau_n,
        "fast_n_steps": fast_n_steps,
        "fast_burn": fast_burn,
        "n_ref_samples": n_ref_samples,
        "min_tail_counts": min_tail_counts,
    }

    with parameters_path.open("w", encoding="utf-8") as handle:
        json.dump(parameters, handle, indent=2)

    print("Saved:", pdf_path)
    print("Saved:", png_path)
    print("Saved:", data_path)
    print("Saved:", parameters_path)


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Generate the type-A-consistent hierarchical Langevin figure."
        )
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("Fig_Langevin_typeA_results"),
        help="Directory in which the figure and numerical data are saved.",
    )
    return parser.parse_args()


def main() -> None:
    """Program entry point."""

    arguments = parse_arguments()
    generate_figure(arguments.output_dir.resolve())


if __name__ == "__main__":
    main()
